
import os

out = []

def L(s=''):
    out.append(s)

L('# PROJECT GUIDE - AI-Powered Gmail Assistant and SQL Agent')
L('## Complete College Review Preparation Guide')
L()
L('> IMPORTANT: Read sections 17-21 tonight. Do NOT skip the Cheat Sheet at the end.')
L()

L('---')
L()
L('## 1. PROJECT OVERVIEW')
L()
L('### Project Title')
L('AI-Powered Gmail Assistant and SQL Agent')
L()
L('### Main Purpose')
L('This is an AI-powered web application that:')
L('1. Reads your Gmail inbox and generates AI replies using Google Gemini AI')
L('2. Provides a Telegram bot that pushes email alerts and allows voice replies')
L('3. Has an AI SQL Agent for database management using plain English')
L('4. Schedules Google Meet meetings automatically from email content')
L('5. Exports a PDF activity report of email interactions')
L()
L('### Problem It Solves')
L('- People miss important emails because inbox is too crowded')
L('- Writing professional replies takes time')
L('- Checking email constantly is distracting')
L('- Scheduling meetings from email threads takes manual effort')
L()
L('### Main Features')
L('1. Google OAuth Login - Sign in with your Google account')
L('2. Gmail Inbox Viewer - See unread emails with AI urgency tags')
L('3. AI Auto-Reply (3 tones: Professional / Friendly / Brief)')
L('4. Email Triage (Urgent / Job / Meeting / College / Noise / Other)')
L('5. Morning Briefing - AI summary of inbox + calendar events')
L('6. Google Meet Scheduler directly from email thread')
L('7. Telegram Bot with text and voice reply support')
L('8. AI SQL Agent - natural language database management')
L('9. PDF Report Export')
L('10. Hybrid MySQL + SQLite Database (auto-switch)')
L()

L('---')
L()
L('## 2. HOW THE PROJECT WORKS')
L()
L('### High-Level Flow')
L('```')
L('USER (Browser) -> FRONTEND (React/Vite) -> BACKEND (Node.js/Express:5000)')
L('                                                    |-> Google APIs + Gemini AI')
L('                                                    |-> Database (SQLite/MySQL)')
L('                                                    |-> Telegram Bot (polls Gmail every 90s)')
L('```')
L()
L('### External Services')
L('| Service | What It Does |')
L('|---------|-------------|')
L('| Google OAuth 2.0 | Sign in with Google (no password needed) |')
L('| Gmail API | Read emails, apply labels, send replies |')
L('| Google Calendar API | Create Google Meet events |')
L('| Google Gemini AI | Generate replies, classify emails, morning briefing |')
L('| Telegram Bot API | Push notifications, receive voice/text commands |')
L('| Vercel | Hosts the React frontend (free) |')
L('| Render | Hosts the Node.js backend (free) |')
L()

L('---')
L()
L('## 3. TECHNOLOGIES USED')
L()
L('| Technology | Used For | Simple Explanation |')
L('|------------|----------|-------------------|')
L('| React 18 | Frontend UI | JavaScript library for building interactive web UIs |')
L('| Vite | Build tool | Fast dev server for React, much faster than Create React App |')
L('| React Router DOM v6 | Navigation | Handles URL routing in the React SPA |')
L('| Axios | HTTP client | Sends API calls from frontend to backend |')
L('| Node.js | Server runtime | Runs JavaScript code on the server |')
L('| Express.js | Web framework | Creates REST API routes and middleware |')
L('| JWT (jsonwebtoken) | Auth tokens | Stateless login sessions (7-day expiry) |')
L('| bcryptjs | Password hashing | One-way hash, cannot be reversed |')
L('| googleapis | Google APIs | Official SDK for Gmail and Calendar |')
L('| @google/generative-ai | Gemini AI | Official Google Gemini SDK |')
L('| node-telegram-bot-api | Telegram | Bot API wrapper for Node.js |')
L('| PDFKit | PDF creation | Generates PDF reports in Node.js |')
L('| MySQL2 | Database (prod) | MySQL connection for production |')
L('| SQLite3 | Database (local) | File-based DB, no server needed |')
L('| dotenv | Config | Loads .env into process.env |')
L('| CORS | Security | Allows frontend to call backend across origins |')
L('| Nodemon | Dev tool | Auto-restarts server when files change |')
L('| Vercel | Deployment | Free hosting for React apps |')
L('| Render | Deployment | Free hosting for Node.js servers |')
L('| Git/GitHub | Version control | Code management + auto-deployment |')
L()

L('---')
L()
L('## 4. PROJECT STRUCTURE')
L()
L('```')
L('Gmail Ai/                       <- Project root (monorepo)')
L('|-- backend/                    <- Node.js Express API server')
L('|   |-- config/db.js            <- Hybrid DB: MySQL primary, SQLite fallback')
L('|   |-- controllers/')
L('|   |   |-- auth.controller.js  <- register, login, Google OAuth flow')
L('|   |   |-- gmail.controller.js <- inbox, briefing, triage, reply, send')
L('|   |   +-- telegram.controller.js <- link code, status')
L('|   |-- middleware/auth.js       <- JWT guard (protects all private routes)')
L('|   |-- models/user.model.js     <- All DB queries for users table')
L('|   |-- routes/')
L('|   |   |-- auth.routes.js       <- /api/auth/*')
L('|   |   |-- gmail.routes.js      <- /api/gmail/*')
L('|   |   |-- telegram.routes.js   <- /api/telegram/*')
L('|   |   |-- calendar.routes.js   <- /api/calendar/*')
L('|   |   |-- agent.js             <- /api/agent/chat (AI SQL Agent)')
L('|   |   |-- pdf.js               <- /api/pdf/gmail-summary')
L('|   |   +-- data.js              <- /api/data/students, /api/data/products')
L('|   |-- services/')
L('|   |   |-- ai.service.js        <- ALL Gemini AI functions')
L('|   |   |-- gmail.service.js     <- Gmail API operations')
L('|   |   |-- calendar.service.js  <- Google Calendar operations')
L('|   |   +-- telegram.service.js  <- Telegram bot (auto-starts on server boot)')
L('|   |-- server.js               <- MAIN ENTRY POINT - starts everything')
L('|   |-- .env                    <- Secret keys (NEVER in Git!)')
L('|   |-- college.db              <- SQLite database file (local mode)')
L('|   +-- package.json            <- Backend npm dependencies')
L('|')
L('|-- frontend/                   <- React + Vite application')
L('|   |-- src/')
L('|   |   |-- components/Navbar.jsx  <- Top navigation bar')
L('|   |   |-- pages/')
L('|   |   |   |-- Login.jsx          <- Email + Google OAuth login')
L('|   |   |   |-- Register.jsx       <- Email registration form')
L('|   |   |   |-- GmailInbox.jsx     <- MAIN PAGE (608 lines!)')
L('|   |   |   |-- Agent.jsx          <- AI SQL Agent chat interface')
L('|   |   |   +-- Dashboard.jsx      <- PDF download + analytics')
L('|   |   |-- App.jsx                <- Router + PrivateRoute guard')
L('|   |   |-- main.jsx               <- React entry point')
L('|   |   +-- index.css              <- All styles (dark glassmorphism theme)')
L('|   |-- vercel.json                <- Proxies /api/* to Render backend')
L('|   +-- package.json')
L('|')
L('|-- gmail-bot/                  <- LEGACY standalone bot (old, single-user)')
L('|   |-- bot.js                  <- Telegram commands (/start, /check, /auth)')
L('|   |-- gmail.js                <- Gmail OAuth via token file (old approach)')
L('|   |-- ai.js                   <- Gemini reply generation')
L('|   +-- db.js                   <- Own DB connection')
L('|')
L('|-- vercel.json                 <- Root Vercel config')
L('|-- README.md                   <- Setup instructions')
L('|-- START_BACKEND.bat           <- Windows batch: cd backend && npm run dev')
L('|-- START_FRONTEND.bat          <- Windows batch: cd frontend && npm run dev')
L('+-- .gitignore                  <- Excludes .env, node_modules, college.db, dist/')
L('```')
L()
L('### Key File Explanations')
L()
L('**server.js**: Main entry. Starts Express, configures CORS, loads all routes, starts Telegram bot.')
L()
L('**config/db.js**: Smart hybrid database. Tries MySQL first. Falls back to SQLite automatically.')
L('Creates all tables on first run. Seeds sample data if tables are empty.')
L()
L('**middleware/auth.js (17 lines!)**: Extracts JWT from Authorization header, verifies signature,')
L('attaches req.user. Returns 401 if invalid. Applied to every protected route.')
L()
L('**services/ai.service.js**: All Gemini-powered features: urgency analysis, email classification,')
L('reply generation, morning briefing, meeting extraction, voice transcription.')
L()
L('**services/telegram.service.js**: Full Telegram bot with commands, voice messages, inline buttons,')
L('and auto Gmail polling every 90 seconds.')
L()
L('**GmailInbox.jsx (608 lines)**: Most important frontend file. Shows inbox, generates AI replies,')
L('handles triage, briefing, Google Meet scheduling, and Telegram linking.')
L()

L('---')
L()
L('## 5. FRONTEND EXPLANATION')
L()
L('### Routes (App.jsx)')
L('- /login -> Login.jsx (PUBLIC)')
L('- /register -> Register.jsx (PUBLIC)')
L('- / and /gmail -> GmailInbox.jsx (PRIVATE - needs JWT)')
L('- /agent -> Agent.jsx (PRIVATE)')
L('- /report -> Dashboard.jsx (PRIVATE)')
L()
L('### PrivateRoute Guard')
L('Checks localStorage.getItem("token") before rendering private pages.')
L('If no token -> navigate("/login"). Also reads token from ?token= URL param (OAuth callback).')
L()
L('### State Management: ONLY React built-in hooks')
L('- useState: holds component-level data (emails list, loading state, reply text, etc.)')
L('- useEffect: runs side effects (fetch data on load, scroll to bottom of chat)')
L('- NO Redux. NO Context API. Each page is self-contained.')
L()
L('### Login.jsx (150 lines)')
L('Two options:')
L('  1. Email form -> POST /api/auth/login -> store JWT -> navigate("/")')
L('  2. Google button -> GET /api/auth/google/login-url -> browser redirect to Google')
L('     -> Google callback -> backend JWT -> frontend reads ?token= -> localStorage')
L()
L('### GmailInbox.jsx (608 lines) - MOST IMPORTANT')
L('State variables: emails, loading, status, selectedEmail, replyText, selectedTone,')
L('                 linkCode, briefing, meetLink, toastMsg, triageDone...')
L('On mount: fetchStatus() checks if Google is connected + fetchEmails() loads unread inbox')
L('Email cards show: sender, subject, snippet, triage badge (color-coded), urgency badge')
L('Reply panel: opens on right when AI Reply clicked, has 3 tone buttons + textarea + send')
L('Top actions: Connect Google, Morning Briefing, Auto-triage, Link Telegram, Export PDF')
L()
L('### Agent.jsx (146 lines)')
L('Chat UI with example prompt chips at the top.')
L('Sends messages to POST /api/agent/chat.')
L('Shows AI reply + "Tools used" section (shows which DB operations were called).')
L('Typing indicator: 3 bouncing dots animation while waiting for response.')
L()
L('### Dashboard.jsx (116 lines) - PDF Report page')
L('3 status cards: AI Urgency Engine, Tone Controls, Telegram Bot status.')
L('Security audit section showing OAuth 2.0 configuration.')
L('Download button calls GET /api/pdf/gmail-summary -> receives blob -> auto-downloads.')
L()
L('### Navbar.jsx (77 lines)')
L('Shows on all private pages. Reads user name/email from localStorage.')
L('Calls /api/auth/me on each route change to refresh user info.')
L('Buttons: Gmail AI Inbox | SQL Agent | Activity PDF Report | Logout')
L()
L('### Frontend Auth Pattern')
L('```')
L('Login:    localStorage.setItem("token", JWT)')
L('          localStorage.setItem("user", JSON.stringify(userObject))')
L('API call: headers: { Authorization: "Bearer " + localStorage.getItem("token") }')
L('Logout:   localStorage.clear() then navigate("/login")')
L('```')
L()

L('---')
L()
L('## 6. BACKEND EXPLANATION')
L()
L('### Startup Order (server.js)')
L('1. dotenv.config() - loads .env into process.env')
L('2. require("./config/db") - connects DB, creates tables, seeds data')
L('3. require("./services/telegram.service") - starts Telegram bot, starts Gmail poller')
L('4. const app = express()')
L('5. app.use(cors({ origin: [...allowed domains...] }))')
L('6. app.use(express.json())')
L('7. Register all routes: app.use("/api/auth", authRouter), etc.')
L('8. app.listen(PORT) - starts HTTP server')
L()
L('### auth.js Middleware (KEY CODE)')
L('```javascript')
L('module.exports = (req, res, next) => {')
L('  const token = req.headers["authorization"]?.split(" ")[1]; // "Bearer TOKEN" -> "TOKEN"')
L('  if (!token) return res.status(401).json({ message: "Unauthorized" });')
L('  try {')
L('    const decoded = jwt.verify(token, process.env.JWT_SECRET);')
L('    req.user = decoded; // { id, name, email } now available in handler')
L('    next();')
L('  } catch (e) {')
L('    return res.status(401).json({ message: "Invalid token" });')
L('  }')
L('};')
L('```')
L()
L('### Route -> Controller Mapping')
L('/api/auth/* -> auth.routes.js -> auth.controller.js')
L('/api/gmail/* -> gmail.routes.js -> gmail.controller.js')
L('/api/telegram/* -> telegram.routes.js -> telegram.controller.js')
L('/api/calendar/* -> calendar.routes.js (calls calendar.service.js directly)')
L('/api/agent/chat -> agent.js (self-contained with Gemini + DB logic)')
L('/api/pdf/* -> pdf.js (self-contained)')
L('/api/data/* -> data.js (simple SELECT queries)')
L()
L('### Controller Pattern')
L('```javascript')
L('const methodName = async (req, res) => {')
L('  try {')
L('    const userId = req.user.id; // from auth.js middleware')
L('    const result = await SomeService.doSomething(userId, req.body);')
L('    res.json({ success: true, data: result });')
L('  } catch (err) {')
L('    res.status(500).json({ message: err.message });')
L('  }')
L('};')
L('```')
L()
L('### .env File')
L('```')
L('PORT=5000')
L('JWT_SECRET=mysecretkey123')
L('FRONTEND_URL=http://localhost:3000')
L('FORCE_SQLITE=1')
L('DB_HOST=localhost')
L('DB_USER=root')
L('DB_PASSWORD=')
L('DB_NAME=college_db')
L('GOOGLE_CLIENT_ID=xxx.apps.googleusercontent.com')
L('GOOGLE_CLIENT_SECRET=xxx')
L('GOOGLE_REDIRECT_URI=http://localhost:5000/api/auth/google/callback')
L('TELEGRAM_BOT_TOKEN=xxx')
L('GEMINI_API_KEY=xxx')
L('GEMINI_MODEL=gemini-3.6-flash')
L('```')
L()

L('---')
L()
L('## 7. DATABASE')
L()
L('### How the Hybrid System Works')
L('config/db.js checks: FORCE_SQLITE=1 OR DB_HOST is localhost?')
L('  YES -> Use SQLite (file: college.db)')
L('  NO  -> Try MySQL at DB_HOST -> success? use MySQL | fail? fall back to SQLite')
L('After connecting: CREATE TABLE IF NOT EXISTS (all 3 tables)')
L('After creating: INSERT seed data if tables are empty')
L()
L('### users Table')
L('| Column | Type | Purpose |')
L('|--------|------|---------|')
L('| id | INT auto | Primary key |')
L('| name | TEXT | Display name |')
L('| email | TEXT UNIQUE | Login identifier |')
L('| password | TEXT | bcrypt hash (NULL for Google OAuth users) |')
L('| google_tokens | TEXT | JSON: {access_token, refresh_token, expiry_date} |')
L('| telegram_chat_id | TEXT | Set when user links Telegram bot |')
L('| telegram_link_code | TEXT | Temp 6-char code shown to user for linking |')
L('| created_at | DATETIME | Registration timestamp |')
L()
L('### students Table (AI Agent demo data)')
L('id | name | email | course | marks')
L('Auto-seeded: Rahul Sharma (CS, 88), Priya Patel (IT, 92), Amit Kumar (Electronics, 79)')
L()
L('### products Table (AI Agent demo data)')
L('id | name | price | quantity')
L('Auto-seeded: Laptop (55000), Wireless Mouse (850), Mechanical Keyboard (2500)')
L()
L('### Why this design?')
L('No foreign keys - keeps it simple. google_tokens stored as JSON string in one column.')
L('telegram_link_code is temporary - cleared after linking is complete.')
L()
L('### CRUD Examples')
L('```sql')
L('-- Register user')
L("INSERT INTO users (name, email, password) VALUES ('Alice', 'alice@g.com', '$2a$10$...');")
L('-- Login check')
L("SELECT * FROM users WHERE email = 'alice@g.com';")
L('-- Save Google tokens')
L("UPDATE users SET google_tokens = '{\"access_token\":\"ya29...\"}' WHERE id = 1;")
L('-- SQL Agent example')
L("DELETE FROM students WHERE id = 3;")
L('```')
L()

L('---')
L()
L('## 8. ALL API ENDPOINTS')
L()
L('| Method | Endpoint | Purpose | JWT? |')
L('|--------|----------|---------|------|')
L('| POST | /api/auth/register | Register with email | No |')
L('| POST | /api/auth/login | Login -> get JWT | No |')
L('| GET | /api/auth/me | Current user profile | Yes |')
L('| GET | /api/auth/google | Start Google OAuth redirect | No |')
L('| GET | /api/auth/google/login-url | Get OAuth URL as JSON | No |')
L('| GET | /api/auth/google/callback | Google sends code here | No |')
L('| GET | /api/gmail/status | Gmail + Telegram linked? | Yes |')
L('| GET | /api/gmail/unread | Emails with AI triage+urgency | Yes |')
L('| GET | /api/gmail/briefing | AI morning briefing | Yes |')
L('| POST | /api/gmail/triage | Apply AI labels to Gmail | Yes |')
L('| POST | /api/gmail/generate-reply | Gemini AI reply | Yes |')
L('| POST | /api/gmail/send-reply | Send via Gmail API | Yes |')
L('| POST | /api/telegram/link-code | Generate 6-char link code | Yes |')
L('| GET | /api/telegram/status | Telegram linked? | Yes |')
L('| GET | /api/calendar/events | Upcoming events | Yes |')
L('| POST | /api/calendar/create | Create Meet event | Yes |')
L('| POST | /api/calendar/schedule-from-email | AI extracts + creates Meet | Yes |')
L('| DELETE | /api/calendar/events/:id | Delete event | Yes |')
L('| POST | /api/agent/chat | AI SQL Agent (NL to DB) | Yes |')
L('| GET | /api/pdf/gmail-summary | Download PDF report | Yes |')
L('| GET | /api/data/students | All students | Yes |')
L('| GET | /api/data/products | All products | Yes |')
L('| GET | / | Health check | No |')
L()

L('---')
L()
L('## 9. COMPLETE USER FLOWS')
L()
L('### Flow 1: Email Registration and Login')
L('```')
L('Visit localhost:3000 -> PrivateRoute -> no token -> redirect /login')
L('Click Register -> fill name, email, password -> submit')
L('  POST /api/auth/register -> bcrypt.hash(pw, 10) -> INSERT users -> 201 Created')
L('  navigate("/login") after 1.5s')
L('Enter email + password -> submit')
L('  POST /api/auth/login -> SELECT user by email -> bcrypt.compare -> match?')
L('  YES: jwt.sign({id, name, email}, SECRET, {expiresIn: "7d"}) -> return {token, user}')
L('  localStorage.setItem("token") -> navigate("/") -> GmailInbox loads')
L('```')
L()
L('### Flow 2: Google OAuth Login')
L('```')
L('Click "Sign in with Google"')
L('  GET /api/auth/google/login-url -> returns OAuth URL as JSON')
L('  window.location.href = url -> browser goes to Google')
L('User picks Google account -> approves Gmail + Calendar permissions')
L('Google redirects to: /api/auth/google/callback?code=AUTH_CODE')
L('Backend:')
L('  oauth2.getToken(code) -> {access_token, refresh_token}')
L('  Google People API -> {name, email}')
L('  SELECT user by email OR INSERT new user')
L('  UPDATE google_tokens in users table')
L('  jwt.sign({id, name, email}) -> create JWT')
L('  res.redirect(FRONTEND_URL + "/gmail?token=" + jwt)')
L('Login.jsx useEffect reads ?token= -> localStorage.setItem("token") -> navigate("/")')
L('```')
L()
L('### Flow 3: Generate and Send AI Reply')
L('```')
L('Click "AI Reply" on an email')
L('  selectedEmail state set -> reply panel appears on right side')
L('  POST /api/gmail/generate-reply {from, subject, snippet, tone:"Professional"}')
L('  -> auth middleware validates JWT')
L('  -> gmail.controller.generateReply()')
L('  -> AIService.generateEmailReply(from, subject, snippet, tone)')
L('  -> Gemini API call: generate reply based on email context and tone')
L('  -> if Gemini fails: return template reply')
L('  -> response: {success:true, reply:"Dear..."}')
L('  -> replyText state updated -> shown in textarea')
L('User can switch tone (Professional/Friendly/Brief) to regenerate')
L('Click "Send reply"')
L('  POST /api/gmail/send-reply {to, subject, threadId, replyText}')
L('  -> GmailService.sendReply()')
L('  -> create base64 encoded MIME email message')
L('  -> gmail.users.messages.send()')
L('  -> Email delivered to recipient')
L('  -> Frontend shows toast: "Reply sent!"')
L('```')
L()
L('### Flow 4: Link Telegram Bot')
L('```')
L('Click "Link Telegram" button')
L('  POST /api/telegram/link-code (with JWT)')
L('  -> UserModel.generateLinkCode(userId)')
L('  -> generate random 6-char alphanumeric code (e.g. "XK7P2M")')
L('  -> UPDATE users SET telegram_link_code = "XK7P2M" WHERE id = userId')
L('  -> return {code: "XK7P2M"}')
L('Frontend shows: "Open Telegram and send: /connect XK7P2M to the bot"')
L('User opens Telegram -> sends /connect XK7P2M')
L('Telegram bot receives message:')
L('  -> parse /connect command -> extract code "XK7P2M"')
L('  -> SELECT user WHERE telegram_link_code = "XK7P2M"')
L('  -> UPDATE users SET telegram_chat_id = chatId, telegram_link_code = NULL')
L('  -> bot.sendMessage(chatId, "Linked! Welcome John")')
L('Now telegram.service.js will push email alerts to this chatId')
L('```')
L()
L('### Flow 5: AI SQL Agent')
L('```')
L('Navigate to /agent')
L('Type: "Show all students with marks above 80"')
L('  POST /api/agent/chat {message: "Show all students with marks above 80"}')
L('  agent.js creates Gemini chat session with tool declarations:')
L('    - read_records(table, filter)')
L('    - create_record(table, data)')
L('    - update_record(table, data, where)')
L('    - delete_record(table, where)')
L('    - list_tables()')
L('  Sends to Gemini -> Gemini analyzes intent')
L('  Gemini returns: functionCall {name:"read_records", args:{table:"students"}}')
L('  Backend: SELECT * FROM students')
L('  Returns rows to Gemini as tool result')
L('  Gemini: filters rows where marks > 80 -> writes final text')
L('  Response: {reply:"There are 2 students: Rahul(88), Priya(92)", steps:[{...}]}')
L('Agent.jsx shows reply + collapsible "Tools used" section')
L('```')
L()
L('### Flow 6: Schedule Meet from Email')
L('```')
L('Click "Schedule Meet" on an email')
L('  POST /api/calendar/schedule-from-email {from, subject, snippet}')
L('  -> AIService.extractMeetingFromEmail(snippet)')
L('     -> Gemini reads email -> extracts: title, datetime, attendees')
L('  -> CalendarService.createMeetingEvent(userId, {title, start, end, attendees})')
L('     -> getValidCalendarClient(userId)')
L('     -> calendar.events.insert with requestId -> Google creates Meet link')
L('  -> Response: {event: {meetLink:"https://meet.google.com/xxx", start:"2024-..."}')
L('Frontend: shows "Meet ready" banner with join link')
L('Auto-fills reply textarea: "I have scheduled a Meet for [time]: [link]"')
L('User can send this reply to confirm the meeting')
L('```')
L()
L('### Flow 7: Telegram Push Alerts')
L('```')
L('server.js requires telegram.service -> startImportantMailWatcher() called')
L('setInterval every 90 seconds -> checkImportantMailForAll()')
L('  SELECT all users WHERE google_tokens IS NOT NULL AND telegram_chat_id IS NOT NULL')
L('  For each user:')
L('    emails = GmailService.fetchInbox(userId)')
L('    for each email:')
L('      triage = AIService.classifyEmail(from, subject, snippet)')
L('      if triage.category in [Urgent, Job, Meeting, College]:')
L('        if emailId not in notifiedSet:')
L('          bot.sendMessage(chatId, emailDetails, {inline_keyboard:[[AI Reply, Voice Reply]]})')
L('          notifiedSet.add(emailId)')
L('User taps "AI Reply" inline button')
L('  -> callbackQuery handler generates Gemini reply')
L('  -> shows reply with "Send" button')
L('User taps "Send"')
L('  -> GmailService.sendReply(userId, threadId, to, subject, replyText)')
L('  -> Email sent from Telegram!')
L('```')
L()

L('---')
L()
L('## 10. AUTHENTICATION AND SECURITY')
L()
L('### Two Login Methods')
L('1. Email + Password: traditional form-based login')
L('2. Google OAuth 2.0: "Sign in with Google" - no password stored for Google users')
L()
L('### bcrypt Password Hashing')
L('```javascript')
L('// Registration')
L('const salt = await bcrypt.genSalt(10); // 10 rounds = 2^10 iterations')
L('const hash = await bcrypt.hash(password, salt); // "$2a$10$xyz..."')
L('// Login')
L('const isValid = await bcrypt.compare(inputPassword, storedHash); // true/false')
L('```')
L('Even if database is stolen, hashes cannot be reversed to get original passwords.')
L()
L('### JWT Flow')
L('```')
L('Creation: jwt.sign({id, name, email}, JWT_SECRET, {expiresIn:"7d"})')
L('          -> creates eyJhbGc....payload....signature')
L('Storage:  localStorage.setItem("token", jwt)')
L('Usage:    axios.get(url, {headers:{Authorization:"Bearer "+token}})')
L('Verify:   jwt.verify(token, JWT_SECRET) -> decoded object OR throws error')
L('Expiry:   After 7 days jwt.verify throws TokenExpiredError -> 401 -> re-login')
L('```')
L()
L('### Google OAuth Scopes Requested')
L('- https://mail.google.com/ (full Gmail access: read, send, modify)')
L('- https://www.googleapis.com/auth/calendar.events (create/delete meetings)')
L('- https://www.googleapis.com/auth/userinfo.email (get email address)')
L('- https://www.googleapis.com/auth/userinfo.profile (get name)')
L()
L('### Token Auto-Refresh')
L('When Google access_token expires (1 hour), googleapis library automatically')
L('calls the refresh endpoint using refresh_token. New tokens are saved back to DB.')
L('This happens transparently - user does not need to re-login.')
L()
L('### Security Checklist')
L('- [x] bcrypt password hashing (10 rounds)')
L('- [x] JWT stateless authentication')
L('- [x] CORS whitelist (not open to all)')
L('- [x] SQL parameterized queries (prevents injection)')
L('- [x] Agent table allowlist (blocks reading users table)')
L('- [x] .env in .gitignore (secrets never committed)')
L('- [ ] Rate limiting (missing - known weakness)')
L('- [ ] Input validation beyond required fields (missing)')
L()

L('---')
L()
L('## 11. DEPLOYMENT')
L()
L('### Frontend -> Vercel')
L('- Build command: npm run build (Vite -> creates dist/)')
L('- Vercel hosts dist/ as static CDN website')
L('- vercel.json rules:')
L('  Rule 1: /api/:path* -> proxied to https://gmail-assistant-1.onrender.com/api/:path*')
L('  Rule 2: /(.*) -> /index.html (all routes serve React app)')
L()
L('### Backend -> Render')
L('- Start command: node server.js (or npm start)')
L('- Environment variables: set in Render dashboard (NOT from .env file)')
L('- Backend URL: https://gmail-assistant-1.onrender.com')
L('- Free tier limitation: sleeps after 15 min inactivity, ~30s cold start')
L()
L('### Database on Render')
L('- If DB_HOST = remote MySQL server: persistent data survives restarts')
L('- If DB_HOST = localhost: SQLite used, data ERASED on restart')
L('- Production fix: use Supabase, PlanetScale, or db4free.net (free MySQL)')
L()
L('### Auto-Deployment')
L('git push origin main -> GitHub detects commit')
L('  -> Vercel: npm run build -> deploy frontend (2 min)')
L('  -> Render: pulls latest, node server.js -> deploy backend (2 min)')
L()

L('---')
L()
L('## 12. GIT AND GITHUB')
L()
L('### Monorepo Structure')
L('One repository contains all: backend/ + frontend/ + gmail-bot/')
L()
L('### .gitignore Excludes')
L('- node_modules/ (install with npm install)')
L('- .env (secret keys - NEVER commit!)')
L('- college.db (local database)')
L('- dist/ (built output)')
L()
L('### Essential Commands')
L('git status           -> see which files changed')
L('git add .            -> stage all changes')
L('git commit -m "msg"  -> create snapshot')
L('git push origin main -> upload to GitHub (triggers deploy)')
L('git pull origin main -> download latest code')
L()
L('### Run Locally')
L('START_BACKEND.bat  -> runs: cd backend && npm install && npm run dev (port 5000)')
L('START_FRONTEND.bat -> runs: cd frontend && npm install && npm run dev (port 3000)')
L('Then open: http://localhost:3000')
L()

L('---')
L()
L('## 13. TOP 15 IMPORTANT FILES')
L()
L('1.  backend/server.js (103 lines) - Main entry, starts DB + Telegram + Express')
L('2.  backend/config/db.js (313 lines) - Hybrid MySQL/SQLite with auto-switch')
L('3.  backend/services/ai.service.js (292 lines) - All Gemini AI functions')
L('4.  backend/services/telegram.service.js (446 lines) - Full Telegram bot + poller')
L('5.  backend/services/gmail.service.js (247 lines) - Gmail API operations')
L('6.  backend/controllers/auth.controller.js (179 lines) - Auth + OAuth flow')
L('7.  backend/controllers/gmail.controller.js (171 lines) - Gmail feature handlers')
L('8.  backend/models/user.model.js (214 lines) - User DB queries (CRUD for users)')
L('9.  backend/middleware/auth.js (17 lines) - JWT guard for private routes')
L('10. backend/routes/agent.js (237 lines) - AI SQL Agent with agentic loop')
L('11. frontend/src/pages/GmailInbox.jsx (608 lines) - MAIN UI page')
L('12. frontend/src/App.jsx (56 lines) - Router + PrivateRoute guard')
L('13. frontend/src/pages/Login.jsx (150 lines) - Email + Google login')
L('14. backend/routes/pdf.js (98 lines) - PDF generation with PDFKit')
L('15. backend/services/calendar.service.js (141 lines) - Google Calendar ops')
L()

L('---')
L()
L('## 14. KEY FUNCTIONS')
L()
L('analyzeUrgency (ai.service.js)')
L('  Input: subject, snippet strings')
L('  Logic: keyword matching (urgent/deadline/asap/interview/critical)')
L('  Output: { level:"HIGH"/"MEDIUM"/"LOW", label:"URGENT", color, bg }')
L()
L('classifyEmail (ai.service.js)')
L('  Input: subject, snippet, from strings')
L('  Logic: regex patterns for each category in priority order')
L('  Output: { category:"Job", gmailLabel:"AI/Job", color, bg }')
L('  Categories: Urgent -> Job -> Meeting -> College -> Noise -> Other')
L()
L('generateEmailReply (ai.service.js)')
L('  Input: from, subject, snippet, tone')
L('  Logic: build Gemini prompt with tone instruction -> call Gemini API')
L('  Output: string (email reply text)')
L('  Fallback: template reply if Gemini unavailable')
L()
L('getValidGmailClient (gmail.service.js)')
L('  Input: userId')
L('  Logic: load google_tokens from DB -> create OAuth2 client -> setCredentials')
L('  Output: authenticated Gmail API client object')
L('  Note: googleapis auto-refreshes expired tokens')
L()
L('fetchInbox (gmail.service.js)')
L('  Input: userId, maxResults=5')
L('  Logic: list unread message IDs -> fetch each full message -> extract headers')
L('  Output: array of { id, threadId, from, subject, snippet, date }')
L()
L('googleCallback (auth.controller.js)')
L('  Input: HTTP request with ?code=AUTH_CODE')
L('  Logic: exchange code -> tokens -> profile -> findOrCreate user -> save tokens -> JWT')
L('  Output: HTTP redirect to FRONTEND_URL/gmail?token=JWT')
L()
L('query adapter (config/db.js)')
L('  Input: SQL string, params array, callback function')
L('  Logic: if activeMode=="mysql" use pool, if "sqlite" use sqliteDb')
L('  Output: callback(error, results) - same API regardless of DB engine')
L()
L('linkTelegramChat (user.model.js)')
L('  Input: code (6-char), chatId (Telegram ID string)')
L('  Logic: find user by telegram_link_code -> UPDATE telegram_chat_id -> clear code')
L('  Output: user object { id, name, email }')
L()
L('checkImportantMailForAll (telegram.service.js)')
L('  Input: none (called by 90s timer)')
L('  Logic: find all users with Google + Telegram linked -> fetch inbox -> classify -> push alerts')
L('  Output: Telegram messages sent (side effect)')
L()
L('Agentic loop (agent.js)')
L('  Input: user message string')
L('  Logic: Gemini chat -> if functionCall: execute DB tool -> send result back -> repeat')
L('         continue until Gemini returns text instead of functionCall (max 10 iterations)')
L('  Output: { reply: "final text", steps: [{tool, args, result}, ...] }')
L()

L('---')
L()
L('## 15. ARCHITECTURE')
L()
L('```')
L('BROWSER')
L('  |-- HTTP + JWT Bearer token')
L('  v')
L('+------------------------------------------+')
L('|  FRONTEND (Vercel CDN)                    |')
L('|  React 18 + Vite + React Router           |')
L('|  Login, Register, GmailInbox, Agent, PDF  |')
L('|  axios /api/* calls -> vercel.json proxy  |')
L('+------------------+-----------------------+')
L('                   |  API rewrite to Render')
L('                   v')
L('+------------------------------------------+')
L('|  BACKEND (Render.com)                     |')
L('|  Node.js + Express.js                     |')
L('|  Routes -> auth.js middleware -> handlers  |')
L('|  +-----------------------------------------|')
L('|  |  SERVICES LAYER                        ||')
L('|  |  ai.service.js     gmail.service.js    ||')
L('|  |  calendar.service  telegram.service    ||')
L('|  +-----------------------------------------|')
L('+-----+----------+-----------+---------------+')
L('      |          |           |')
L('      v          v           v')
L('+--------+  +-----------+  +----------+')
L('|DATABASE|  |GOOGLE APIS|  |TELEGRAM  |')
L('|SQLite  |  |Gmail API  |  |BOT API   |')
L('|or MySQL|  |Calendar   |  |          |')
L('+--------+  |OAuth2     |  +----+-----+')
L('            +-----+-----+       |')
L('                  |             | push alerts')
L('                  v             v every 90s')
L('           +----------+   +-----------+')
L('           |GEMINI AI |   | USERS     |')
L('           |API       |   | TELEGRAM  |')
L('           +----------+   | APP       |')
L('                          +-----------+')
L('```')
L()

L('---')
L()
L('## 16. DATA FLOWS')
L()
L('### Email Reply Data Flow')
L('```')
L('GmailInbox.jsx: user clicks AI Reply')
L('  -> POST /api/gmail/generate-reply {from, subject, snippet, tone}')
L('  -> authMiddleware validates JWT -> req.user = {id, name, email}')
L('  -> gmail.controller.generateReply(req, res)')
L('  -> AIService.generateEmailReply(from, subject, snippet, tone)')
L('  -> Gemini API prompt: "Generate a {tone} reply to email from {from} about {subject}..."')
L('  -> Gemini returns text response')
L('  -> {success:true, reply:"Dear..."}')
L('  -> replyText state updated -> shown in textarea')
L('User clicks Send Reply')
L('  -> POST /api/gmail/send-reply {to, subject, threadId, replyText}')
L('  -> GmailService.getValidGmailClient(userId)')
L('  -> construct MIME message -> base64url encode')
L('  -> gmail.users.messages.send()')
L('  -> email delivered')
L('  -> frontend: toast "Reply sent!"')
L('```')
L()
L('### AI SQL Agent Data Flow')
L('```')
L('User types: "Show all students"')
L('  -> POST /api/agent/chat {message: "Show all students"}')
L('  -> agent.js: create Gemini model with tool declarations')
L('  -> chat.sendMessage("Show all students")')
L('  -> Gemini analyzes -> returns: functionCall{read_records, {table:"students"}}')
L('  -> backend: db.query("SELECT * FROM students")')
L('  -> returns: [{name:Rahul, marks:88}, ...]')
L('  -> send tool result back to Gemini chat')
L('  -> Gemini formulates text: "Here are 3 students: ..."')
L('  -> {reply:"Here are 3 students...", steps:[{tool:"read_records", args:{...}}]}')
L('Agent.jsx: displays reply text + "Tools used" collapsible panel')
L('```')
L()

L('---')
L()
L('## 17. REVIEW QUESTIONS (77 TOTAL)')
L()
L('### BASIC QUESTIONS (1-10)')
L('1. What is the full name and purpose of your project?')
L('2. Which language is used for the frontend?')
L('3. Which language is used for the backend?')
L('4. What is Node.js?')
L('5. What is React.js?')
L('6. What does API stand for? What is REST API?')
L('7. What is the difference between frontend and backend?')
L('8. What database did you use?')
L('9. What is JSON?')
L('10. What is npm?')
L()
L('### PROJECT QUESTIONS (11-20)')
L('11. What does your project actually do?')
L('12. How many main modules or parts does your project have?')
L('13. Why did you choose to build a Gmail Assistant?')
L('14. How does the AI know what to reply to emails?')
L('15. What is the AI SQL Agent?')
L('16. What happens when you click "AI Reply" on an email?')
L('17. What is the "Morning Briefing" feature?')
L('18. What is email triage? What categories?')
L('19. How does the Telegram bot know about Gmail emails?')
L('20. Can a user use this without a Google account?')
L()
L('### FRONTEND QUESTIONS (21-30)')
L('21. What is Vite? Why not Create React App?')
L('22. What is React Router? How does it work?')
L('23. What is JSX?')
L('24. What are React Hooks? Which did you use?')
L('25. Explain useState with an example from your code.')
L('26. Explain useEffect with an example from your code.')
L('27. How does the frontend handle authentication?')
L('28. What is localStorage? Why use it?')
L('29. How does frontend communicate with backend?')
L('30. What is Axios? How different from fetch?')
L()
L('### BACKEND QUESTIONS (31-43)')
L('31. What is Express.js?')
L('32. What is middleware? Give an example from your project.')
L('33. What is the purpose of auth.js middleware?')
L('34. What is CORS and why configure it?')
L('35. What is server.js responsible for?')
L('36. Difference between a route and a controller?')
L('37. What is dotenv?')
L('38. What does nodemon do?')
L('39. How does your backend handle errors?')
L('40. What are environment variables?')
L('41. What is the MVC pattern? Does your project follow it?')
L('42. What is CORS? Why is it needed?')
L('43. What is a callback function in Node.js?')
L()
L('### DATABASE QUESTIONS (44-51)')
L('44. What is SQLite vs MySQL?')
L('45. Why support both SQLite and MySQL?')
L('46. What tables are in your database?')
L('47. What is the google_tokens column?')
L('48. How does the database get created automatically?')
L('49. What is AUTO_INCREMENT?')
L('50. What is a primary key?')
L('51. What is CRUD?')
L()
L('### API AND AUTH QUESTIONS (52-62)')
L('52. What is OAuth 2.0?')
L('53. What is a JWT token?')
L('54. Difference between POST and GET?')
L('55. How do you protect an API endpoint?')
L('56. What happens at /api/auth/google/callback?')
L('57. What is a Bearer token?')
L('58. How does the Telegram link code work?')
L('59. What does /api/agent/chat do?')
L('60. What HTTP status codes do you return?')
L('61. What is the JWT expiry time?')
L('62. How is Google token refreshed automatically?')
L()
L('### DEPLOYMENT QUESTIONS (63-69)')
L('63. Where is frontend deployed?')
L('64. Where is backend deployed?')
L('65. What is vercel.json for?')
L('66. What does the rewrite rule do?')
L('67. What happens to SQLite data when Render restarts?')
L('68. How are API keys stored in production?')
L('69. How does auto-deployment work?')
L()
L('### SECURITY QUESTIONS (70-77)')
L('70. How are passwords stored?')
L('71. What is bcrypt?')
L('72. What if someone gets your JWT_SECRET?')
L('73. What is SQL injection? How do you prevent it?')
L('74. What OAuth scopes does your project request?')
L('75. Why is CORS needed?')
L('76. What security measures does your project have?')
L('77. Why is rate limiting missing and what would you add?')
L()

L('---')
L()
L('## 18. ANSWERS TO KEY QUESTIONS')
L()
L('Q1: What is the purpose of your project?')
L('  "My project is an AI-powered Gmail Assistant. It reads Gmail emails, generates AI replies')
L('  using Google Gemini, classifies emails into categories (Urgent/Job/Meeting/College/Noise),')
L('  schedules Google Meet meetings from email content, and sends Telegram push notifications')
L('  for important emails. There is also an AI SQL Agent that lets users manage the database')
L('  using plain English commands."')
L()
L('Q4: What is Node.js?')
L('  "Node.js is a JavaScript runtime that lets you run JavaScript on the server side, not just')
L('  in the browser. It is built on Chromes V8 engine. I use it for my backend server because')
L('  it is non-blocking and handles many concurrent requests efficiently."')
L()
L('Q5: What is React?')
L('  "React is a JavaScript library by Facebook for building user interfaces. It uses components')
L('  - reusable pieces of UI. When data (state) changes, React efficiently updates only the')
L('  affected parts of the page using a Virtual DOM. In my project every page is a React component."')
L()
L('Q6: What is REST API?')
L('  "REST API is a set of conventions for building HTTP APIs. REST uses HTTP methods - GET to')
L('  retrieve data, POST to create, PUT/PATCH to update, DELETE to remove. Resources are')
L('  accessed via URLs like /api/users. My backend follows REST: GET /api/gmail/unread returns')
L('  emails, POST /api/gmail/generate-reply creates an AI reply."')
L()
L('Q21: What is Vite?')
L('  "Vite is a modern build tool for React. It is 10-100x faster than Create React App because')
L('  it uses native ES modules during development instead of bundling everything upfront.')
L('  npm run dev starts the dev server instantly. npm run build creates the optimized dist/.')
L('  Vercel hosts that dist/ folder as a static website."')
L()
L('Q31: What is Express.js?')
L('  "Express is a minimal web framework for Node.js. Without it, I would need to write complex')
L('  low-level Node.js HTTP code. With Express, I just write app.get(path, handler) to create')
L('  API endpoints. It handles routing, middleware chaining, and request/response objects."')
L()
L('Q32: What is middleware?')
L('  "Middleware is a function that runs BEFORE your route handler. It has access to request,')
L('  response, and a next() function. My best example is auth.js - every protected route runs')
L('  this first. It verifies the JWT token. If valid, calls next() to proceed. If invalid,')
L('  sends 401 Unauthorized and stops. This avoids duplicating auth logic in every handler."')
L()
L('Q44: SQLite vs MySQL?')
L('  "SQLite is a file-based database - the whole database is one file (college.db). No separate')
L('  server or installation needed, perfect for local development. MySQL is a client-server database')
L('  that runs as a separate service, better for production with many concurrent users. My project')
L('  config/db.js tries MySQL first and if unavailable automatically switches to SQLite.")
L()
L('Q52: What is OAuth 2.0?')
L('  "OAuth 2.0 is the industry standard for sign in with Google type authentication. Instead of')
L('  giving me your Google password, you authenticate directly with Google. Google then gives my')
L('  app temporary tokens to access your Gmail on your behalf. Flow: my app redirects to Google')
L('  -> you approve permissions -> Google sends a code to my backend -> I exchange it for tokens.')
L('  I never see your password."')
L()
L('Q53: What is JWT?')
L('  "JSON Web Token. When you login, my backend creates a JWT containing your user ID and email,')
L('  signs it with a secret key, and sends it to the frontend. The token has 3 parts separated by')
L('  dots: header.payload.signature. Every API request includes this token. My backend verifies')
L('  the signature - if anyone tampers with the payload, the signature becomes invalid and')
L('  jwt.verify throws an error. Unlike sessions, JWTs dont need database lookups."')
L()
L('Q70: How are passwords stored?')
L('  "Never as plain text. I use bcrypt which is a one-way hashing algorithm. During registration:')
L('  bcrypt.hash(password, 10) produces a string like $2a$10$abc... that cannot be reversed.')
L('  The 10 means 2^10 = 1024 hashing iterations. During login: bcrypt.compare(input, stored)')
L('  returns true or false. Even if an attacker steals the database, they cannot get passwords."')
L()
L('Q73: SQL injection and prevention?')
L('  "SQL injection is when malicious SQL code is put in an input. If I wrote')
L('  query = "SELECT * FROM users WHERE email = " + email, an attacker could type')
L('  email = \' OR 1=1 -- and get ALL users. I prevent this with parameterized queries:')
L('  db.query("SELECT * FROM users WHERE email = ?", [email]). The ? is a placeholder -')
L('  the DB driver treats the value as data, not executable SQL code."')
L()
L('Q67: SQLite data loss on Render?')
L('  "This is a real known limitation. Renders free tier uses ephemeral storage - the SQLite')
L('  file is deleted on every restart or redeploy. Users registered with email/password would')
L('  lose their accounts. The fix is connecting a persistent MySQL database (Supabase, Railway,')
L('  or db4free.net). My code already handles this - set DB_HOST to any remote MySQL server.")
L()

L('---')
L()
L('## 19. EXPLAIN IN 2 MINUTES')
L()
L('"My project is the AI-Powered Gmail Assistant and SQL Agent.')
L()
L('Users log in with their Google account using OAuth 2.0. The app fetches their unread Gmail')
L('messages and uses keyword analysis to tag each email as Urgent, Job, Meeting, College, or Noise.')
L()
L('One click on AI Reply generates a Professional, Friendly, or Brief email reply using Google')
L('Gemini AI. The user can edit it and send it directly from the web app.')
L()
L('The Morning Briefing feature gives a one-paragraph AI summary of all unread emails plus')
L('upcoming calendar events. If an email involves a meeting, one click schedules a Google Meet')
L('and auto-fills the reply with the link.')
L()
L('A Telegram bot runs in the background, checking Gmail every 90 seconds. If an important email')
L('arrives, you get a push notification on your phone. You can even reply using a voice message')
L('from Telegram - the AI transcribes it and sends the reply.')
L()
L('Finally, the AI SQL Agent lets you type plain English like Add student Alice with marks 90')
L('and the database gets updated automatically.')
L()
L('Tech: React + Vite frontend on Vercel, Node.js + Express backend on Render, Google Gemini AI,')
L('hybrid SQLite/MySQL database."')
L()

L('---')
L()
L('## 20. EXPLAIN IN 5 MINUTES')
L()
L('"Good morning. I will present my project - the AI-Powered Gmail Assistant and SQL Agent.')
L()
L('PROBLEM STATEMENT: People receive 50-100 emails daily. Reading, categorizing, and replying')
L('takes significant time. Scheduling meetings from email threads requires manual coordination.')
L()
L('TECH STACK:')
L('- Frontend: React 18 with Vite build tool, React Router DOM v6, Axios')
L('- Backend: Node.js with Express.js framework')
L('- Auth: Google OAuth 2.0 + JWT tokens (bcrypt for email/password)')
L('- AI: Google Gemini via @google/generative-ai official SDK')
L('- Google APIs: googleapis library for Gmail and Calendar')
L('- Bot: node-telegram-bot-api for Telegram integration')
L('- Database: Hybrid - SQLite locally, MySQL in production')
L('- Deployment: Vercel (frontend) + Render (backend) via GitHub CI/CD')
L()
L('AUTHENTICATION:')
L('Two options: email+password (bcrypt hashed) or Google OAuth 2.0.')
L('JWT tokens with 7-day expiry are stored in localStorage and sent as Bearer tokens.')
L('All private routes are protected by the auth.js middleware.')
L()
L('GMAIL INTEGRATION:')
L('After Google login, OAuth tokens are stored in the database. The googleapis library')
L('uses these tokens to access Gmail on the users behalf. Access tokens auto-refresh.')
L()
L('AI FEATURES:')
L('1. Email urgency analysis using keyword matching (fast, no API cost)')
L('2. Email classification into 6 categories using regex patterns')
L('3. AI reply generation: Gemini generates Professional/Friendly/Brief replies')
L('4. Morning Briefing: Gemini narrative of inbox + calendar events + suggestions')
L('5. Meeting extraction: Gemini reads email -> creates Google Calendar event with Meet link')
L('6. Voice reply: Gemini multimodal transcribes Telegram voice to email text')
L()
L('TELEGRAM BOT:')
L('Runs inside the Express backend - no separate server. Every 90 seconds, checks all users')
L('with linked Gmail and Telegram accounts. Sends push notifications for Urgent/Job/Meeting')
L('emails with inline action buttons. Users can approve AI replies from Telegram.')
L()
L('AI SQL AGENT:')
L('Natural language interface for database operations. Gemini is given tool declarations')
L('(read_records, create_record, etc.). An agentic loop keeps calling tools until Gemini')
L('gives a final text answer. Security: only students and products tables allowed.')
L()
L('DATABASE:')
L('3 tables: users (auth + tokens), students (demo), products (demo).')
L('Hybrid: tries MySQL first, falls back to SQLite. Tables auto-created on startup.')
L()
L('DEPLOYMENT:')
L('Frontend on Vercel, backend on Render. Both connected to GitHub for auto-deployment.')
L('vercel.json proxies all /api/* to Render backend. React Router is handled by serving')
L('index.html for all routes.')
L()
L('Thank you. I am happy to demonstrate or answer questions."')
L()

L('---')
L()
L('## 21. DEMO SEQUENCE')
L()
L('### Pre-Demo Checklist')
L('- Backend running (START_BACKEND.bat or check Render URL responds)')
L('- Frontend running (START_FRONTEND.bat or check Vercel URL)')
L('- Login credentials ready')
L('- Know these Agent commands: "Show all students", "Add student named [name] marks 95"')
L()
L('### Step-by-Step Demo')
L()
L('Step 1: Login Page')
L('  Show dark glassmorphism UI, gradient title, two login options')
L()
L('Step 2: Login')
L('  Login with credentials -> show JWT in localStorage (DevTools -> Application -> Local Storage)')
L('  "The JWT token is now stored and will be sent with every API call"')
L()
L('Step 3: Gmail Inbox')
L('  Point to email list: "Each card shows sender, subject, and AI-generated category badges"')
L('  Show triage badge (colored: Job=blue, Urgent=red, Meeting=teal, College=purple)')
L('  Show urgency badge (HIGH/MEDIUM/LOW)')
L()
L('Step 4: AI Reply Demo')
L('  Click AI Reply -> reply panel appears on right')
L('  "This reply was generated by Gemini AI based on the email content"')
L('  Click Professional -> Friendly -> Brief to show tones')
L('  Edit text if needed -> optionally click Send Reply')
L()
L('Step 5: Morning Briefing')
L('  Click "Morning Briefing" -> wait for Gemini to process')
L('  "Here is the AI narrative summarizing all emails and upcoming events"')
L()
L('Step 6: Auto-Triage')
L('  Click "Auto-triage Labels"')
L('  "This applied Gmail labels (AI/Urgent, AI/Job) directly in your Gmail account"')
L()
L('Step 7: AI SQL Agent')
L('  Navigate to SQL Agent (click in navbar)')
L('  Click "Show all students" chip')
L('  Show response + Tools used section')
L('  Type: "Add student named [your name], email test@test.com, course CS, marks 95"')
L('  Show confirmation -> click Show all students again to verify')
L()
L('Step 8: PDF Report')
L('  Click Activity PDF Report -> click Download button -> open downloaded PDF')
L()
L('Step 9: Architecture')
L('  Draw diagram: Browser -> Vercel -> Render -> Google APIs + Gemini -> DB')
L('  "GitHub connects both Vercel and Render for auto-deployment"')
L()

L('---')
L()
L('## 22. MEMORIZE TONIGHT')
L()
L('TOP 30 FACTS:')
L()
L('1.  Project: AI-Powered Gmail Assistant and SQL Agent')
L('2.  Frontend stack: React 18 + Vite + React Router DOM v6 + Axios')
L('3.  Backend stack: Node.js + Express.js')
L('4.  AI library: @google/generative-ai (Gemini)')
L('5.  Google API library: googleapis')
L('6.  Database: Hybrid - SQLite (local/fallback) / MySQL (production)')
L('7.  Auth method 1: Email + bcrypt (10 rounds)')
L('8.  Auth method 2: Google OAuth 2.0')
L('9.  Session: JWT tokens (7-day expiry) stored in localStorage')
L('10. JWT sent as: "Authorization: Bearer <token>" header')
L('11. Email categories: Urgent / Job / Meeting / College / Noise / Other')
L('12. Telegram polls Gmail: every 90 SECONDS')
L('13. AI SQL Agent: natural language -> Gemini -> tool call -> SQL -> DB result')
L('14. PDF: generated with PDFKit library on the backend')
L('15. Frontend deployed: VERCEL')
L('16. Backend deployed: RENDER')
L('17. vercel.json: rewrites /api/* to Render backend URL')
L('18. SQLite limitation: data lost on Render restart (ephemeral storage)')
L('19. Gmail labels: AI/Urgent, AI/Job, AI/Meeting, AI/College, AI/Noise, AI/Other')
L('20. Google scopes: mail.google.com + calendar.events + userinfo')
L('21. DB tables: users, students, products (auto-created and auto-seeded)')
L('22. PrivateRoute: checks localStorage token before rendering')
L('23. Backend port: 5000 | Frontend dev port: 5173 (or 3000)')
L('24. authMiddleware (17 lines): validates JWT on EVERY protected route')
L('25. google_tokens column: JSON string with access_token + refresh_token')
L('26. Voice reply: Telegram voice -> Gemini multimodal -> email text -> send')
L('27. Google Meet: created via Calendar API with hangoutsMeet conference type')
L('28. Agent fallback: regex parser if GEMINI_API_KEY not set')
L('29. gmail-bot/ = LEGACY (single user, token file) - kept for reference')
L('30. telegram.service.js = PRODUCTION bot (multi-user, DB-based tokens)')
L()

L('---')
L()
L('## 23. WEAK POINTS TO PREPARE FOR')
L()
L('### Weak Point 1: Weak JWT_SECRET')
L('Teacher: "Your JWT secret is mysecretkey123 - that is weak!"')
L('Answer: "Absolutely correct. The .env.example value is only for local development. In the')
L('Render dashboard, the actual JWT_SECRET is a 64-character random hex string. If compromised,')
L('an attacker could forge tokens. Best practice: use short-lived tokens (15 min) with refresh tokens."')
L()
L('### Weak Point 2: No Rate Limiting')
L('Teacher: "Can someone spam your API with 10,000 requests?"')
L('Answer: "Yes, this is a known limitation. I would add the express-rate-limit package to limit')
L('each IP to ~100 requests per 15 minutes. For academic demonstration this is acceptable,')
L('but I am aware it needs to be added for production."')
L()
L('### Weak Point 3: SQLite Data Loss on Render')
L('Teacher: "What happens when Render restarts?"')
L('Answer: "Email/password users lose their accounts because Render free tier uses ephemeral storage.')
L('Google OAuth users are safer - they auto-recreate on next login. The fix is a persistent MySQL.')
L('My code already supports this - just set DB_HOST to any remote MySQL server like Supabase."')
L()
L('### Weak Point 4: Two Telegram Implementations')
L('Teacher: "Why do you have gmail-bot/ AND backend/services/telegram.service.js?"')
L('Answer: "gmail-bot/ was the original prototype for a single user - it used a shared token.json.')
L('The backend/services/telegram.service.js is the improved multi-user version using per-user')
L('tokens from the database. The old version is kept for reference and comparison."')
L()
L('### Weak Point 5: No Input Validation')
L('Teacher: "What if someone sends a huge string as email content?"')
L('Answer: "Currently I only check required fields. I should add express-validator or Joi to')
L('enforce length limits. The Gmail API has its own limits so extreme inputs would fail there,')
L('but proper validation should be at my API level."')
L()

L('---')
L()
L('## 24. PROJECT LIMITATIONS')
L()
L('1. SQLite data wipes on Render restart (ephemeral storage)')
L('2. No rate limiting - API can be abused')
L('3. Gemini model name "gemini-3.6-flash" may be invalid (graceful fallback to templates)')
L('4. Telegram dedup uses in-memory Set (resets on restart = duplicate alerts possible)')
L('5. No email pagination - only 10 most recent unread emails')
L('6. No user profile editing (name, email, password change)')
L('7. CORS is too permissive (all *.vercel.app instead of specific domain)')
L('8. PDF "AI replies count" = email count, not actual tracked metric')
L('9. No email search functionality')
L('10. Two Telegram implementations adds confusion')
L()

L('---')
L()
L('## 25. FUTURE SCOPE')
L()
L('1. Persistent MySQL (Supabase/Railway) - fix data loss')
L('2. Email search and filter by sender, subject, date')
L('3. Email pagination (load more)')
L('4. Web push notifications (browser alerts without Telegram)')
L('5. Multilingual support (Gemini handles multiple languages)')
L('6. Auto-reply rules ("send brief reply to all Noise emails automatically")')
L('7. Real analytics (track actual reply counts, response times)')
L('8. User settings page (update profile, revoke Google access)')
L('9. Personal reply templates library')
L('10. Rate limiting + input validation + security hardening')
L('11. WhatsApp integration via Twilio API')
L('12. Smart scheduling (check free/busy before proposing meeting time)')
L('13. Multi-account Gmail support per user')
L('14. React Native mobile app using same backend API')
L()

L('---')
L()
L('## 26. FINAL CHEAT SHEET')
L()
L('### ONE LINE DESCRIPTION')
L('AI web app that reads Gmail, generates Gemini AI replies, classifies emails into 6 categories,')
L('schedules Google Meet, sends Telegram push alerts, and manages database via natural language AI.')
L()
L('### TECH STACK')
L('| Layer | Technologies |')
L('|-------|-------------|')
L('| Frontend | React 18 + Vite + React Router v6 + Axios |')
L('| Backend | Node.js + Express.js + JWT + bcrypt |')
L('| AI | @google/generative-ai (Gemini) |')
L('| APIs | googleapis (Gmail + Calendar) |')
L('| Bot | node-telegram-bot-api |')
L('| PDF | PDFKit |')
L('| Database | SQLite3 (local/fallback) + MySQL2 (production) |')
L('| Deploy FE | Vercel |')
L('| Deploy BE | Render |')
L('| Code | Git + GitHub (monorepo) |')
L()
L('### ARCHITECTURE IN 3 LINES')
L('Browser -> Vercel (React) -> vercel.json proxy -> Render (Node.js/Express)')
L('Backend -> Google APIs (Gmail, Calendar, OAuth) + Gemini AI + Telegram Bot API')
L('Backend -> SQLite or MySQL (auto-switch, tables auto-created)')
L()
L('### DATABASE TABLES')
L('users:    id, name, email, password(bcrypt), google_tokens(JSON), telegram_chat_id, link_code')
L('students: id, name, email, course, marks  (DEMO for AI SQL Agent)')
L('products: id, name, price, quantity        (DEMO for AI SQL Agent)')
L()
L('### EMAIL CATEGORIES')
L('URGENT (red)    - urgent, deadline, ASAP, immediately, critical, important')
L('JOB (blue)      - interview, offer, hiring, opportunity, apply, placement')
L('MEETING (teal)  - meeting, schedule, call, discussion, sync, standup')
L('COLLEGE (purple) - assignment, exam, semester, submission, faculty, college')
L('NOISE (gray)    - newsletter, unsubscribe, promo, discount, offer, deal')
L('OTHER (yellow)  - everything else')
L()
L('### IMPORTANT API ROUTES')
L('POST /api/auth/register        - Register with email')
L('POST /api/auth/login           - Login -> JWT')
L('GET  /api/auth/google/login-url - Start Google OAuth')
L('GET  /api/gmail/unread         - Emails with AI tags')
L('POST /api/gmail/generate-reply - Gemini AI reply')
L('POST /api/gmail/send-reply     - Send via Gmail')
L('GET  /api/gmail/briefing       - Morning AI summary')
L('POST /api/gmail/triage         - Apply Gmail labels')
L('POST /api/calendar/schedule-from-email - AI -> Meet')
L('POST /api/agent/chat           - Natural language DB')
L('GET  /api/pdf/gmail-summary    - Download PDF')
L()
L('### TOP 10 Q&A')
L()
L('Q: What does your project do?')
L('A: AI Gmail assistant - reads emails, Gemini AI replies, Telegram alerts, natural language SQL Agent.')
L()
L('Q: What is JWT?')
L('A: JSON Web Token - signed user ID string. Stored in localStorage, sent as Bearer token.')
L()
L('Q: What is OAuth 2.0?')
L('A: "Sign in with Google" standard. User logs in at Google, Google gives my app Gmail tokens.')
L()
L('Q: How are passwords stored?')
L('A: bcrypt hashed (10 rounds). Irreversible. bcrypt.compare checks on login.')
L()
L('Q: What is the AI SQL Agent?')
L('A: Chat interface - type English (Show all students) -> Gemini calls DB tools -> SQL executes.')
L()
L('Q: How does Telegram bot work?')
L('A: Runs inside backend, polls Gmail every 90s, pushes alerts for Urgent/Job/Meeting/College emails.')
L()
L('Q: What is the hybrid database?')
L('A: config/db.js tries MySQL first. If unavailable -> auto fallback to SQLite. Same code for both.')
L()
L('Q: How is project deployed?')
L('A: Frontend on Vercel, Backend on Render. vercel.json proxies /api/* to Render URL.')
L()
L('Q: What is email triage?')
L('A: AI classifies email into 6 categories and applies Gmail labels (AI/Urgent, AI/Job, etc.)')
L()
L('Q: What is Morning Briefing?')
L('A: Gemini reads all unread emails + calendar events, writes 2-3 paragraph summary + suggestions.')
L()
L('---')
L()
L('Guide created: 2026-08-19 | Based on complete source code analysis of c:\\Gmail Ai')
L('Backend Production URL: https://gmail-assistant-1.onrender.com')
L('All 26 sections covered. Good luck with your review!')

with open('PROJECT_GUIDE.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(out))

lines = len(out)
size = len('\n'.join(out))
print(f'SUCCESS: PROJECT_GUIDE.md written! Lines={lines}, Size={size/1024:.1f} KB')

