const express = require('express');
const PDFDocument = require('pdfkit');
const authMiddleware = require('../middleware/auth');
const GmailService = require('../services/gmail.service');
const UserModel = require('../models/user.model');

const router = express.Router();

// GET /api/pdf/gmail-summary - Generate Gmail AI Activity PDF Report
router.get('/gmail-summary', authMiddleware, async (req, res) => {
  try {
    const user = await UserModel.findById(req.user.id);
    if (!user || !user.google_tokens) {
      return res.status(401).json({ message: 'Google not connected. Sign in with Google first.' });
    }
    const emails = await GmailService.fetchInbox(req.user.id, 15);

    const doc = new PDFDocument({ margin: 40 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=Gmail_AI_Activity_Report.pdf');
    doc.pipe(res);

    // Document Title
    doc.fontSize(20).fillColor('#4f46e5').text('Gmail AI Assistant — Activity Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#64748b').text(`User: ${user ? user.name : 'College Student'} (${user ? user.email : 'user@example.com'})`, { align: 'center' });
    doc.fontSize(10).fillColor('#888888').text(`Report Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.moveDown(1.5);

    // Summary Box
    const startY = doc.y;
    doc.rect(40, startY, 520, 50).fill('#f8fafc');
    doc.fillColor('#1e293b').fontSize(11).text(`• Total Emails Processed: ${emails.length}`, 55, startY + 15);
    doc.text(`• AI Auto-Replies Generated: ${emails.length}`, 240, startY + 15);
    doc.text(`• Telegram Status: ${user && user.telegram_chat_id ? 'Linked 🟢' : 'Pending 🟡'}`, 55, startY + 30);

    doc.moveDown(2.5);

    // Table Header
    const tableTop = doc.y;
    doc.rect(40, tableTop, 520, 22).fill('#4f46e5');
    doc.fillColor('#ffffff').fontSize(10);
    doc.text('Sender', 50, tableTop + 6, { width: 140 });
    doc.text('Subject', 200, tableTop + 6, { width: 220 });
    doc.text('AI Status', 440, tableTop + 6, { width: 100 });

    doc.moveDown(0.8);

    // Rows
    emails.forEach((email, i) => {
      if (doc.y > 700) {
        doc.addPage();
      }
      const y = doc.y;
      const bg = i % 2 === 0 ? '#f1f5f9' : '#ffffff';
      doc.rect(40, y, 520, 24).fill(bg);
      doc.fillColor('#1e293b').fontSize(9);
      doc.text((email.from || 'Sender').substring(0, 26), 50, y + 7, { width: 140 });
      doc.text((email.subject || 'Subject').substring(0, 40), 200, y + 7, { width: 220 });
      doc.fillColor('#059669').text('Auto-Drafted', 440, y + 7, { width: 100 });
      doc.moveDown(0.4);
    });

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#94a3b8').text('Generated by Gmail AI Assistant College Project', { align: 'center' });
    
    // Finalize PDF
    doc.end();

  } catch (err) {
    console.error('PDF Error:', err.message);
    if (!res.headersSent) {
      res.status(500).json({ message: 'Error generating PDF report: ' + err.message });
    }
  }
});

module.exports = router;
